erDiagram
  direction TB

  Person
  Personroll
  Rolltilldelning
  Fil
  Filtyp
  Regelverk
  Dokumentdel
  Rad
  Dokumenttyp
  Annoteringsjobb
  Annoteringsenhet
  Annotering
  Texttyp
  Annoteringsenhetsstatus
  Annoteringsenhetstyp
  Annoteringsjobbstyp
  Annoteringsstatus
  Modell
  KB

  Person ||--{ Rolltilldelning
  Personroll ||--{ Rolltilldelning

  Person ||--{ Annoteringsjobb
  Personroll ||--{ Fil

  Fil ||--|| Filtyp
  Fil ||--|| Regelverk
  Fil ||--{ Dokumentdel

  Dokumentdel ||--{ Rad
  Rad ||--|| Dokumenttyp

  Dokumentdel ||--{ Annoteringsjobb
  Annoteringsjobb ||--{ Annoteringsenhet
  Annoteringsenhet ||--{ Annotering

  Annotering ||--|| Texttyp
  Annotering ||--|| Annoteringsstatus
  Annoteringsenhet ||--{ Texttyp
  Annoteringsenhet ||--|| Annoteringsenhetstyp
  Annoteringsenhet ||--{ Annoteringsenhetsstatus
  Annoteringsjobb ||--|| Annoteringsjobbstyp
  Annoteringsenhet ||--|| Modell

  Annoteringsenhet ||--{ KB
  Rad ||--{ KB
